### ISSUE TITLE
Separate code package and data

### ISSUE THREAD

**Issue by xrotwang** [lingpy/sinopy#6]
https://github.com/lexibank/pylexibank/issues/215#issuecomment-617077329

**Comment by LinguList** [comment]
I have as a first attempt separated major functions into four packages.

1. seaquence.py works with lingpy dependencies only
2. hanzi.py has character operations that require some data (unicode, unihan)
3. yinyun.py mostly provides access to data, with few essential operations
4. data.py stays the same (the point we have to discuss what to do essentially)

I have also added rudimentary tests (in form of simple print statements)

**Comment by LinguList** [comment]
I have thought a bit about this now, and I think now, that it may be sufficient to just take the script that is called "seaquence.py" and place it into the lingpy package, for completeness? Operations all rely on lingpy there, it adds a bit more code to test, but we have basically two functions, plus the profile-writing function could be added to lingpy.sequence.profile.

**Comment by LinguList** [comment]
In this way we could spare the data discussion. Sinopy could offer wrappers of these functions to not lose backwards compatibility. And it would be easier to develop sinopy as a package useful for Chinese character manipulation and the like, while lingpy would do the sequence operations.

I think I may have time to make a PR for lingpy during this week.

**Comment by xrotwang** [comment]
I'll have a look to figure out what exactly in lingpy is required. I'm not entirely against adding this to lingpy, but if there's a chance to have any of this standalone, that would be my prefered solution. I'm a bit afraid that if we treat lingpy simply as a big bag to ship code, it will become messy quickly (e.g. because it becomes more and more difficult to decide what is an internal and what is an external interface).

**Comment by xrotwang** [comment]
E.g. if the functionality in `seaquence.py` took `tokens`, `soundclasses` and `prosodic_strings` as input, it could probably be fully decouple from lingpy; i.e. it would be the responsibility of the caller to use lingpy (or something else?) to provide suitable input.

**Comment by LinguList** [comment]
Sure. On the other hand: lingpy's core functions are to deal with sequences, with these functions like ipa2tokens, and the like. So the function `get_structure`, which essentially guesses the prosodic structure of a SEAquence would fit well in there. 

On the other hand, the code for generating preliminary orthoprofiles might be put somewhere else, since this is not necessarily the major concern of lingpy, where one may say: lingpy is for analysis AFTER one has a profile.

**Comment by xrotwang** [comment]
Yes, "lingpy's core functions are to deal with sequences", so let's make sequences the external interface. With the `segments` package we already have a separate source of sequences (independent of lingpy), so I'd argue `seaquence` could be a separate consumer of sequences. The fact that lingpy has both - source and consumer - functionality shouldn't lead us to think everything related to sequences should go into lingpy, right?

**Comment by LinguList** [comment]
Well, the get_structure function and the `parse_chinese_morphemes` (bad name) are core functions to *deal* with sequences. The core is `parse_chinese_morphemes`, as it guesses the prosodic structure of a given phonetic sequence in ipa or a bit beyond that. And this serves to evaluate if a sequence conforms to our expectations when dealing with SEA languages.

So if one places this functionality into a package that evaluates sequences, it would make sense to break out also the sound class models, as well as the ipa2tokens, etc. from core lingpy, since these are doing very similar things in the same spirit, just with the difference, that `parse_chinese_morphemes` is specific for SEA languages (but future may bring us even more code to deal with other language families as well).

**Comment by LinguList** [comment]
So to summarize my view on this, if we say that `segments` produces sequences, lingpy currently produces them (with `ipa2tokens`, important for initial profiles), while at the same time also comparing them (alignments, etc.) and evaluating them (and this includes conversions to sound classes, guessing prosodic aspects, etc.). It would certainly be good to make a clearer distinction between all these, i.e., sequence comparison, sequence curation, and sequence analysis (maybe there are better terms). But the major code in `seaquence.py`, the code we use to evaluate data in SEA languages in lexibank, would qualify as `sequence analysis`.

**Comment by xrotwang** [comment]
Maybe we should use this issue to get to a more transparent architecture - modeled around the central concept of a *sequence* as a `list` of tokens. I see the following aspects of "manipulating" sequences:

*Segmentation*: The process of getting from text to sequences.

Then there seem to be several kinds of *sequence analysis*:
- *sequence annotation*: "converting" sequences to sound classes, prosodic strings, etc. An annotated sequence could be considered just a special case of a sequence.
- *sequence comparison*: Relates two or more sequences to compute similarity.

We could now either
- make lingpy pluggable, i.e. whenever lingpy functionality does now call `ipa2tokens`, it should instead lookup which implementation of segmentation is to be used, and use that, or
- only expose simple building blocks as API, with clear interfaces, i.e. a segmenter looks like
  ```python
  def segment(text) -> sequence
  ```
  an annotator looks like
  ```python
  def annotate(sequence) -> sequence (of annotations)
  ```

I'd be leaning towards the second option, in particular because it can be implemented with only specifying what text and sequence is.

**Comment by xrotwang** [comment]
I think the second option described above would also play well with the lingpy `Wordlist` infrastructure: E.g. you could use segmenters and annotators (or compositions of these) from third-party packages as argument of [`add_entries`](https://github.com/lingpy/lingpy/blob/2fb197e81515cc02d74d31896c0be26b702219a4/lingpy/basic/parser.py#L280).

**Comment by LinguList** [comment]
Yes, this looks in fact quite well, and the three-way distinction is very important to clear one's head about the mix of functions that are currently assembled in lingpy.

Even simply restructuring what is there now, by separating packages for "annotate", "segmentation", and "comparison" would make the code base more transparent.

**Comment by LinguList** [comment]
So what we obviously do now in seaquence is an annotation of sequences. And we would need this functionality in other cases as well, e.g., when trying to get cv instances for prosody, etc.

**Comment by LinguList** [comment]
The problem of a function like `parse_chinese_morpheme`, however, is that the sequence can be modified during annotation. 

```python
In [1]: from sinopy.seaquence import parse_chinese_morphemes                                                                                                             
In [2]: parse_chinese_morphemes('t a i ⁵')                                                                                                                               
Out[2]: ['t', '-', 'ai', '-', '⁵']
```

But one can argue that this is wrong, and it is in fact leading to a fail in our evaluation, since the number of expected segments (4) is not the same as the number of parsed segments (3). 

One can capture failure in other ways, e.g., saying that "i" should not occur in coda position.

**Comment by xrotwang** [comment]
Maybe that's *resegmentation* then? I.e. *segmentation* which works on sequences in addition to text?

**Comment by LinguList** [comment]
Yes, resegmentation. And we use it for checking a sequence's segmentation. In fact: we have "segment", "annotate", "compare", and we need also "test". And obviously: segment, annotate, and compare all can contribute to test.

**Comment by LinguList** [comment]
Ah, and resegmentation is in fact crucial in some tasks. Think of "tokens2morphemes" in lingpy, which adds morpheme boundaries to a sequence.

**Comment by xrotwang** [comment]
*Test* to me is just a particular type of *analysis* where the result is a `bool`.

**Comment by LinguList** [comment]
As some kind of an "oberbegriff", I would say that "sequence manipulation" captures the aspect of re-segmentation and sequence annotation (plus test). The call signature is `manipulate(sequence) -> sequence`.

**Comment by LinguList** [comment]
Should we try and start a small package devoted only to this? We could call it `phosema` for "phonetic sequence manipulation". Or `lisema` for "linguistic sequence manipulation`? and we could start with some of the functions discussed?

**Comment by LinguList** [comment]
OR, and I think this also would make a lot of sense, we leave string manipulation with lingpy, where it also always has been an integrative part (and the extended basictypes, like lists, strings, ints, etc. have also long since been added there), but we separate the sequence module by splitting the sound_classes module into the parts as discussed before. `ipa2tokens` would then belong to `sequence.segment`, `tokens2class` would belong to `sequence.manipulate`, and alignment could stay where it is, I think.

**Comment by xrotwang** [comment]
You do mean a separate python package, **not** dependent on lingpy, right? We could call this "linsen" (almost German for "linguistics" and "sequences" :) ).
And I'd be more explicit and strict in such a package. So `tokens2class` would probably be a function `linsen.annotate.soundclass` or similar.

**Comment by LinguList** [comment]
Yes, not dependent on lingpy, rather, something that lingpy could pull in as dependency, also for mainaining backwards-compatibility (e.g, lingpy could provide a wrapper called tokens2class, as long as we don't go for lingpy3, which is unlikely, given all the other things we have to do).

**Comment by xrotwang** [comment]
Yes, good idea. That's probably the smoothest way forward.

**Comment by LinguList** [comment]
I'd go for "linse", easier to pronounce, available on pypi, and we could host it at github.com/lingpy/linse.

And as basic packages, I'd say:

- segment (hosting ipa2tokens equivalent)
- annotate
- manipulate (=resegment, but a bit broader, involves also something like consonant classes, where a sequence is only taken for its first two consonants, etc/)
- evaluate

?

**Comment by LinguList** [comment]
Okay, my arguments for the name don't make sense, as "linsen" is also available on pypi, but I like that it sounds like "rinse" in English, and "rinse" is cleaning, right? So to "linse" linguistic sequences is what we do to a great part...

**Comment by xrotwang** [comment]
I thought about "linse", too. Fine with me.

**Comment by LinguList** [comment]
Should I try and make a first skeleton? This may in fact also allow us to pull lingpy out of the lexibank dependencies, which would be useful, given its size and the dependencies it has itself, so I'd try to make this with minimal dependencies.

**Comment by xrotwang** [comment]
Making the repos is enough, I can do the package skeleton.

**Comment by xrotwang** [comment]
@LinguList I'm just putting together the package skeleton. You could maybe put together a list of lingpy functions which should have most of their logic go into linse.

**Comment by LinguList** [comment]
Yep, sorry, was diving in some other problems, but will do that now.

**Comment by LinguList** [comment]
I'll close this issue, we reconvene in another spot, and sinopy will be more targeted for Chinese characters, where the separation of data is not that easy, but also not urgent...
